### ISSUE TITLE
Unable to find "generate_route.sh"

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#1]
In the instruction for "STACK2: SVL2021.3+Apollo Master" it says "put `generate_route.sh` inside apollo".

Where is `generate_route.sh`?

**Comment by AIasd** [comment]
Hi @YuqiHuai, you can ignore this file since It is not currently used. I will also remove it from the instruction for now.

**Comment by YuqiHuai** [comment]
Thanks for letting me know!
