### ISSUE TITLE
No Module Named Carla

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#10]
https://github.com/AIasd/ADFuzz/blob/d876574293d783b51a6a3086a10e4e998cd5d79e/svl_script/analysis.py#L8

Hi,
For the line referenced above, you might need to add "svl_script.object_types" to import from the correct file.
`from svl_script.object_types import static_types, pedestrian_types, vehicle_types`

Otherwise it will show a "No Module Named 'carla'" error.

The import is correct in other files.

**Comment by AIasd** [comment]
Thanks for the suggestion. Will update it. I did not add that since I usually used it inside the `svl_script` folder.

**Comment by YuqiHuai** [comment]
Ah I see. Thank you for considering the suggestion.
