### ISSUE TITLE
I want to know the specifications of your machine.

### ISSUE THREAD

**Issue by dk-kling** [AIasd/ADFuzz#12]
Hello,
I'm very grateful for your research.
And I want to use your tool, `ADFuzz`.
So, I want to know the specifications of your machine.
May I know which CPU and GPU you used to execute the experiment?
If you use different machines in `SVL` and `CARLA`, I wonder the specifications of each.

Thank you.

**Comment by AIasd** [comment]
I use i9-7940x for CPU and 2080Ti for GPU. They work for both `SVL` and `CARLA`.

**Comment by dk-kling** [comment]
Thank you for your reply!
Have a good day :)
