### ISSUE TITLE
How to run a bug simulation using this tool in the CARLA simulator

### ISSUE THREAD

**Issue by dk-kling** [AIasd/ADFuzz#16]
Hello, thank you for making such a wonderful tool.

I was able to use this tool to run fuzzing and get the following data.

![image](https://user-images.githubusercontent.com/46366411/160045864-f8f57948-019d-45d8-a078-9589c26f88bc.png)

I would like to know if I can see this scenario in CARLA simulator with this data.

If possible, how can I do this?

**Comment by dk-kling** [comment]
I would like to rerun the scenario (with visualization) after the fuzzing process!

**Comment by AIasd** [comment]
Hi @dk-kling ,
I have pushed an update on the rerunning functionality for CARLA-LBC. You can check out the new README for the command regarding it.

**Comment by dk-kling** [comment]
Thank you very much for your help and your kind comment!
Have a good day :)
