### ISSUE TITLE
Question about the bind_socket in svl_script/simulation_utils.py

### ISSUE THREAD

**Issue by MingfeiCheng** [AIasd/ADFuzz#17]
Hello, 

I have a problem about your implementation of receive_zmq method in svl_script/simulation_utils.py. I find that you used sockets to receive messages. But I don't know who are the message sender, which I didn't find in this project. Can you provide any details? Thank you!

**Comment by AIasd** [comment]
The senders will be set up on the Apollo side as covered in the step "STACK2: SVL2021.3+Apollo Master-Setup-Add channel_extraction".

**Comment by MingfeiCheng** [comment]
> The senders will be set up on the Apollo side as covered in the step "STACK2: SVL2021.3+Apollo Master-Setup-Add channel_extraction".

Thank you!
