### ISSUE TITLE
How to generate a scenario that the object is set using the authentic x/y/z coordinate system

### ISSUE THREAD

**Issue by dk-kling** [AIasd/ADFuzz#18]
Hello.
I have questions while experimenting with generating several scenarios using ADFuzz.

As far as I understand, `customized_bounds_and_distributions` in the `scene_configs.py` file, will specify the constraints of the scenario. If so, can I create the scenario situation that I want by modifying the file?

In this case, how does ADFuzz set the location of other vehicles(not ego-vehicle), obstacles, or pedestrians?
(I wonder how constraints such as `"pedestrian_x_min_0"` make the position of the object.)

And can I set it to an absolute position using OpenDRIVE's essential x/y/z coordinate system? (similar to setting customized_routes in scene_configs.py)

Thank you!

**Comment by AIasd** [comment]
Yes, you can. 

The main idea is to set min and max for the field to use to be the same. For example, `pedestrian_x_min_0` and `pedestrian_x_max_0` are both set to 12 so x of the pedestrian's initial position will be 12. This value is with respect to `pedestrian_center_transform_0: ('absolute_location', -150.4, -35.6)` in the dictionary "customized_center_transforms" which is an absolute center coordinate one can specify.

```
    "go_straight_town07_one_ped": {
        "customized_parameters_bounds": {
            "friction_min": 0.9,
            "friction_max": 0.9,

            "num_of_weathers_min": 0,
            "num_of_weathers_max": 0,

            "num_of_static_min": 0,
            "num_of_static_max": 0,
            "num_of_pedestrians_min": 1,
            "num_of_pedestrians_max": 1,
            "num_of_vehicles_min": 0,
            "num_of_vehicles_max": 0,

            "pedestrian_x_min_0": -12,
            "pedestrian_x_max_0": 12,
            "pedestrian_y_min_0": -12,
            "pedestrian_y_max_0": 12,
            "pedestrian_yaw_min_0": 0,
            "pedestrian_yaw_max_0": 360,
            "pedestrian_speed_min_0": 0,
            "pedestrian_speed_max_0": 3,
            "pedestrian_trigger_distance_min_0": 20,
            "pedestrian_trigger_distance_max_0": 20,
            "pedestrian_dist_to_travel_min_0": 50,
            "pedestrian_dist_to_travel_max_0": 50,
            "num_of_pedestrian_types_min_0": 0,
            "num_of_pedestrian_types_max_0": 0,


            # "vehicle_x_min_0": -10,
            # "vehicle_x_max_0": 10,
            # "vehicle_y_min_0": -2,
            # "vehicle_y_max_0": 2,

        },
        "customized_parameters_distributions": {},
        "customized_center_transforms": {
        # "pedestrian_center_transform_0": ("waypoint_ratio", 50),
        'pedestrian_center_transform_0': ('absolute_location', -150.4, -35.6),
        },
        "customized_constraints": [],
        # start: (-151, -60), end: (-151, -15)
    },
```

**Comment by dk-kling** [comment]
Thank you for your kind reply!

I have some questions in your answer.

If, as you said, I set `pedestrian_x_min_0 ` and `pedestrian_x_max_0` to 12, and `absolute_location` to `(-150.4, -35.6)` , will the pedestrian's location of x be set to -150.4 instead of 12?
(because absolute_location has higher priority than pedestrian constraints( `pedestrian_x_min` ,  `pedestrian_x_max` )? )

Additionally, is the value set to pedestrian's constraints ( `pedestrian_x_min` ,  `pedestrian_x_max` ) the same as location of the authentic x/y/z coordinate system(absolute location)?

I don't think that is not true, then what does `pedestrian_x_min`, `pedestrian_x_max` decide?

**Comment by AIasd** [comment]
12 will be added to -150.4. `pedestrian_x_min` and `pedestrian_x_max` represent the bounds of the relative x coordinate (w.r.t. -150.4) the fuzzer will generate. Thus, if they are set to be the same, only that single value (12) will be used.

**Comment by dk-kling** [comment]
Thank you for your answer.
Have a good day!
