### ISSUE TITLE
More detail regarding model_id

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#2]
Hi!
I am able to get ADFuzz up and running, and I do see crashes! But I have some questions!

```
Create Apollo Master in Vehicles

SVL does not have a default "Apollo Master" for "Lincoln2017MKZ" under "Vehicles". To create one, one can duplicate "Apollo 5.0" and then add sensors "Clock Sensor" and "Signal Sensor" from "Apollo 6.0 (modular testing)".
Other preparation

Need to change the field model_id in svl_specific to one's own model_id on svl web UI.
```

For this specific section, can you please add more details to it? I am not sure if I am doing the correct things, and here are some more detailed questions for you.

For "Create Apollo Master in Vehicles"
- is this referring to adding a "Sensor Configurations" for Lincoln2017MKZ in LGSVL? and to do so, we "Add New Configuratoin" by uploading the configuration for both Apollo 5.0 (full analysis) and Apollo 6.0 (modular testing). In other words, combining 2 configurations?

For "Other prepartion"
- where specifically would we be modifying `model_id`? Is it at line 529 where we would write `model_id="ID_OF_NEW_CONFIGURATION_CREATED_ABOVE"`?
- After updaing `svl_specific.py`, it looks like we also need to update `simulation_utils.py` because line 115-140 will consider the new ID as unknown. Is this correct?

Thank you in advance for your response!

**Comment by AIasd** [comment]
Hi @YuqiHuai ,

I have added some details in README. Please take a look and let me know if there is still any confusion. Thanks!

Also, if you are interested in potential collaborations on relevant research projects, I am also always happy to talk.

**Comment by YuqiHuai** [comment]
Hi @AIasd ,
Thank you for adding the details! Everything looks good now! Thank you for always responding fast! I will definitely be talking with you more in the future.
