### ISSUE TITLE
Argument algorithm_name

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#3]
Hello again! Hope you are doing well!
I spent some more time looking at the command line arguments and I am confused with `algorithm_name`

Supported algorithms are:  1. AutoFuzz (GA-UN-NN-GRAD), 2. NSGA2-SM, 3. NSGA2-DT, 4. AV-Fuzzer.
But by reading the code I see `algorithm_name` can be any of: 
```
- random
- random-un
- avfuzzer
- nsga2
- nsga2-un-dt
- nsga2-dt
- nsga2-un
- naga2-emcmc
- nsga2-un-emcmc
```
1. Am I missing any possible input for `algorithm_name`?
2. Can you label supported algorithm with its corresponding `algorithm_name`?

Thank you in advance!

**Comment by AIasd** [comment]
Hi @YuqiHuai , I have updated the readme with key relevant parameters for the supported algorithms. Please have a look.

**Comment by YuqiHuai** [comment]
Thank you for the update! They are very clear to me now.
