### ISSUE TITLE
LGSVL pedestrian not showing up in Apollo

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#6]
Hi! Hope you are doing well!

I have been watching the scenarios in Dreamview when ADFuzz is running and I never see pedestrian being recognized in Apollo.

I am running Apollo 6.0 with the following command
```
python ga_fuzzing.py --simulator svl --n_gen 1 --pop_size=1 --algorithm_name nsga2-un --rank_mode adv_nn --ego_car_model apollo_6_modular --route_type 'BorregasAve_left' --scenario_type 'turn_left_one_ped_and_one_vehicle'
```

Is there some setting in Apollo that I need to change to make pedestrian show up in Dreamview? I played some random LGSVL scenario and I see pedestrians being recognized.

![Image from iOS](https://user-images.githubusercontent.com/34195403/152875841-7732589a-3bbc-4df7-a71d-08cc4a24e5fe.png)

**Comment by AIasd** [comment]
Hi @YuqiHuai ,

This is [a known issue](https://github.com/lgsvl/simulator/issues/1915) of SVL2021.3. You can try an earlier version if you want to use modular testing. The random traffic works because the pedestrians are controlled differently.  And unfortunately, this bug won't be fixed by the SVL team since they plan to sunset the simulator.

**Comment by YuqiHuai** [comment]
Thank you for the response!

**Comment by diaokaitian** [comment]
> Hi @YuqiHuai ,
> 
> This is [a known issue](https://github.com/lgsvl/simulator/issues/1915) of SVL2021.3. You can try an earlier version if you want to use modular testing. The random traffic works because the pedestrians there are implemented differently(in the SVL source code). And unfortunately, this bug won't be fixed by the SVL team since they plan to sunset the simulator. Alternatively, you can also try to fix it by modifying the SVL source code and building from source.


hello,which version can works ok,except 2020.6?

**Comment by AIasd** [comment]
Hi @diaokaitian 

I believe 2021.3 and 2021.2 do not work. Maybe you can try 2021.1?(I forgot if this one work or not). Also, if you use Apollo with the perception module turned on (i.e., not the modular testing one), the pedestrian should be able to be detected.
