### ISSUE TITLE
on_collision agent2 is None

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#7]
Hello again!
I have been running ADFuzz for a longer time and started seeing collisions with other vehicles.

However, for function on_collision (https://github.com/AIasd/ADFuzz/blob/main/svl_script/simulation_utils.py#L62), the function raises an exception when agent2 is None, because line 81&82 does not check if agent2 is None.

I have watched the scenario and the ego vehicle collided with a truck.

Do you know if this is another LGSVL bug like the one yesterday?

**Comment by AIasd** [comment]
Hi @YuqiHuai ,

Thanks for bringing it up! I have pushed a tentative fix for the error (have not run comprehensive tests on it yet). 
Yes, that's another issue of SVL. You can consider to adjust their source code to change this behavior but that might lead to other issues.
