### ISSUE TITLE
Agent '.....' is missing bridge

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#8]
Hi,

For some reason when running ADFuzz I have been seeing bridge throwing errors

```
Agent '9c067880-ceaa-49f5-a705-e9e6365be6ab' is missing bridge client
```

For the section "Other preparation" in the readme file, do we have to change every ID specified here?
```
    if ego_car_model == 'apollo_6_with_signal':
        model_id = '9272dd1a-793a-45b2-bff4-3a160b506d75'
    elif ego_car_model == 'apollo_6_modular':
        model_id = '2e9095fa-c9b9-4f3f-8d7d-65fa2bb03921'
    elif ego_car_model == 'apollo_6_modular_2gt':
        model_id = 'f0daed3e-4b1e-46ce-91ec-21149fa31758'
    elif ego_car_model == 'apollo_6':
        model_id = 'c354b519-ccf0-4c1c-b3cc-645ed5751bb5'
    else:
        print('ego car model is invalid:', ego_car_model)
        raise
```

I used to be able to run ADFuzz by using apollo_6_modular without changing anything, but could not do so today. Is it because the vehicle ID changed in LGSVL?

**Comment by AIasd** [comment]
Hi @YuqiHuai , thank you for the great suggestion! I will update the scripts accordingly.

**Comment by AIasd** [comment]
I believe that id ('2e9095fa-c9b9-4f3f-8d7d-65fa2bb03921' for apollo_6_modular) should be belong to the SVL official content and I can still use it... So I am not sure what happened regarding that.

**Comment by YuqiHuai** [comment]
Got it. I checked ID carefully yesterday and it is indeed there.
What happened was, I was calling ADFuzz using apollo 6 modular, then in the try catch block that attempts to add vehicle 3 times, when the script is adding the ego car to the simulator, it says
Agent id xxxxx is missing, and xxxxx is different and random for 3 tries, which is super weird.

**Comment by YuqiHuai** [comment]
Thanks for adding the suggested script! Very easy to add new vehicles now.

**Comment by YuqiHuai** [comment]
```
ego car model is: apollo_6 



receive zmq
start binding sockets
/home/yhuai/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/bin/sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
finish binding sockets
Agent '335b7b5d-2a31-4c22-b4ea-5cd7f6e0febb' is missing bridge client
fail to spin up apollo, try again!
Agent 'e25a1f1a-7323-4ecd-9494-748ad235c5a5' is missing bridge client
fail to spin up apollo, try again!
Agent '88fa3140-c317-4c6f-bdcd-64e670cb3bdf' is missing bridge client
fail to spin up apollo, try again!
```

**Comment by YuqiHuai** [comment]
I added some print statements like following
```
while times < 3:
        try:
            state = lgsvl.AgentState()
            state.transform = start
            print('model_id', model_id) # added
            ego = sim.add_agent(model_id, lgsvl.AgentType.EGO, state)
            ego.connect_bridge(BRIDGE_HOST, BRIDGE_PORT)
            ego.on_collision(on_collision)
            ..........
        except Exception as e:
            print(e) # added
            print('fail to spin up apollo, try again!')
            times += 1
``` 
and got the following output
```
finish binding sockets
model_id c354b519-ccf0-4c1c-b3cc-645ed5751bb5
Agent 'a76fae48-8642-4a8a-a723-8ed2fe8dcb09' is missing bridge client
fail to spin up apollo, try again!
model_id c354b519-ccf0-4c1c-b3cc-645ed5751bb5
Agent 'b90edcfb-10ea-4671-b1bb-59e6faed5761' is missing bridge client
fail to spin up apollo, try again!
model_id c354b519-ccf0-4c1c-b3cc-645ed5751bb5
Agent '88480a6d-e6ab-44a6-a55a-406506222852' is missing bridge client
fail to spin up apollo, try again!
```

Do you know what might have gone wrong for sim.add_agent to keep using random model_id?

**Comment by AIasd** [comment]
The problem might be caused by the access issue. "c354b519-ccf0-4c1c-b3cc-645ed5751bb5" was created by me so you may not have access to it. Does it appear on your page? Also, did you see similar issues if you use '9272dd1a-793a-45b2-bff4-3a160b506d75' or 'f0daed3e-4b1e-46ce-91ec-21149fa31758'? Those were also created by me.

**Comment by YuqiHuai** [comment]
I tried 4901c017-0c18-4522-ba61-ce76cf0f9f91 which is apollo 6 created by me and I saw the same issue. Can it be LGSVL failed to retrieve vehicle information from svl cloud?

**Comment by AIasd** [comment]
Sorry for the late reply! You can probably try a minimal script as shown in`https://www.svlsimulator.com/docs/python-api/dreamview-api/` with your vehicle id. If the same issue happens, you can open an issue on svl's github and see what they say about it.

**Comment by YuqiHuai** [comment]
Hi! Thanks for the suggestion! I guess there must be weird issues. Today I tried again and this issue no longer exists, the latency problem also does not exist anymore.
