### ISSUE TITLE
Localization problem with Apollo & LGSVL

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#9]
![Screenshot from 2022-02-17 12-00-29](https://user-images.githubusercontent.com/34195403/154565959-3d80afc9-7262-4daf-8077-9b2d1586b529.png)
![Screenshot from 2022-02-17 12-22-12](https://user-images.githubusercontent.com/34195403/154565963-33fa3c05-61a9-4f74-b19b-53a1b4f9ced6.png)

I have see this issue a couple times previously and I am not sure if you have seen this type of issue before, but it is the same every time on my machine.

In Apollo's dreamview the car has not crossed the intersection yet, but in LGSVL the car is way farther than what Apollo shows.
Is there some additional configuration that I need to be aware of?

Commands Used:
```
python ga_fuzzing.py --simulator svl --n_gen 1 --pop_size=1 --algorithm_name nsga2-un --rank_mode adv_nn --ego_car_model apollo_6 --route_type 'BorregasAve_left' --scenario_type 'turn_left_one_ped_and_one_vehicle'
```
Code changed:
```
            model_id="2e9095fa-c9b9-4f3f-8d7d-65fa2bb03921" # Apollo 6.0 (modular testing)
            ego = sim.add_agent(model_id, lgsvl.AgentType.EGO, state)
            ego.connect_bridge(BRIDGE_HOST, BRIDGE_PORT)
            ego.on_collision(on_collision)
```
with the most recent Apollo and ADFuzz.

**Comment by AIasd** [comment]
Hi @YuqiHuai , what CPU and GPU you used for it? Also, you only used modular testing (no perception part) for it right? Usually such delay happens when there is high latency of certain modules of Apollo. However, from the screenshot your provided, it seems the module communication is fine.

**Comment by YuqiHuai** [comment]
Hi, I am using an alienware 17R5, core i7 with gtx 1070. It is not meeting the minimum requirement but this issue did not happen before. lately this started occuring, thanks for the suggestion, I'll try to see how I can resolve this latency issue.

**Comment by YuqiHuai** [comment]
I took a closer look and it seems to be an issue with Apollo. The Localization module cannot be turned on.

**Comment by AIasd** [comment]
Hi @YuqiHuai , if you run the modular testing one, 1070 should be fine. 

In your screenshot, the localization has low latency, which seems to be turned on? Have you figured out the issue?

**Comment by YuqiHuai** [comment]
I am a bit confused as if I should turn on sim control or not. I have set up ADFuzz on my machine previously without turning on sim control and everything was working fine.

**Comment by AIasd** [comment]
You are not supposed to manually turn on Apollo modules since those were handled by the code. However, it is possible that sometimes things do not work...Especially if you run fuzzing for several times without restarting Apollo. In that case you can try to exit Apollo and restart everything.

**Comment by YuqiHuai** [comment]
Thanks for the answer! Is it true that DreamView need to be in "MkZ LGSVL" mode to operate correclty?

**Comment by AIasd** [comment]
This one is used in `[the SVL documentation](https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/)`. I have not tried others.

**Comment by YuqiHuai** [comment]
Thanks for the information! Not sure what happened, I did not change anything but the issue is gone.
